import React, { useState } from 'react';
import Select from 'react-select';

const TypeSelect1 = (props) => {
    const options = [
        { value: 'AED', label: 'UAE Dirham', country: 'United Arab Emirates' },
        { value: 'AFN', label: 'Afghan Afghani', country: 'Afghanistan' },
        { value: 'ALL', label: 'Albanian Lek', country: 'Albania' },
        { value: 'AMD', label: 'Armenian Dram', country: 'Armenia' },
        { value: 'ANG', label: 'Netherlands Antillian Guilder', country: 'Netherlands Antilles' },
        { value: 'AOA', label: 'Angolan Kwanza', country: 'Angola' },
        { value: 'ARS', label: 'Argentine Peso', country: 'Argentina' },
        { value: 'AUD', label: 'Australian Dollar', country: 'Australia' },
        { value: 'AWG', label: 'Aruban Florin', country: 'Aruba' },
        { value: 'AZN', label: 'Azerbaijani Manat', country: 'Azerbaijan' },
        { value: 'BAM', label: 'Bosnia and Herzegovina Mark', country: 'Bosnia and Herzegovina' },
        { value: 'BBD', label: 'Barbados Dollar', country: 'Barbados' },
        { value: 'BDT', label: 'Bangladeshi Taka', country: 'Bangladesh' },
        { value: 'BGN', label: 'Bulgarian Lev', country: 'Bulgaria' },
        { value: 'BHD', label: 'Bahraini Dinar', country: 'Bahrain' },
        { value: 'BIF', label: 'Burundian Franc', country: 'Burundi' },
        { value: 'BMD', label: 'Bermudian Dollar', country: 'Bermuda' },
        { value: 'BND', label: 'Brunei Dollar', country: 'Brunei' },
        { value: 'BOB', label: 'Bolivian Boliviano', country: 'Bolivia' },
        { value: 'BRL', label: 'Brazilian Real', country: 'Brazil' },
        { value: 'BSD', label: 'Bahamian Dollar', country: 'Bahamas' },
        { value: 'BTN', label: 'Bhutanese Ngultrum', country: 'Bhutan' },
        { value: 'BWP', label: 'Botswana Pula', country: 'Botswana' },
        { value: 'BYN', label: 'Belarusian Ruble', country: 'Belarus' },
        { value: 'BZD', label: 'Belize Dollar', country: 'Belize' },
        { value: 'CAD', label: 'Canadian Dollar', country: 'Canada' },
        { value: 'CDF', label: 'Congolese Franc', country: 'Democratic Republic of the Congo' },
        { value: 'CHF', label: 'Swiss Franc', country: 'Switzerland' },
        { value: 'CLP', label: 'Chilean Peso', country: 'Chile' },
        { value: 'CNY', label: 'Chinese Renminbi', country: 'China' },
        { value: 'COP', label: 'Colombian Peso', country: 'Colombia' },
        { value: 'CRC', label: 'Costa Rican Colon', country: 'Costa Rica' },
        { value: 'CUP', label: 'Cuban Peso', country: 'Cuba' },
        { value: 'CVE', label: 'Cape Verdean Escudo', country: 'Cape Verde' },
        { value: 'CZK', label: 'Czech Koruna', country: 'Czech Republic' },
        { value: 'DJF', label: 'Djiboutian Franc', country: 'Djibouti' },
        { value: 'DKK', label: 'Danish Krone', country: 'Denmark' },
        { value: 'DOP', label: 'Dominican Peso', country: 'Dominican Republic' },
        { value: 'DZD', label: 'Algerian Dinar', country: 'Algeria' },
        { value: 'EGP', label: 'Egyptian Pound', country: 'Egypt' },
        { value: 'ERN', label: 'Eritrean Nakfa', country: 'Eritrea' },
        { value: 'ETB', label: 'Ethiopian Birr', country: 'Ethiopia' },
        { value: 'EUR', label: 'Euro	European', country: 'Union' },
        { value: 'FJD', label: 'Fiji Dollar', country: 'Fiji' },
        { value: 'FKP', label: 'Falkland Islands Pound', country: 'Falkland Islands' },
        { value: 'FOK', label: 'Faroese Króna', country: 'Faroe Islands' },
        { value: 'GBP', label: 'Pound Sterling', country: 'United Kingdom' },
        { value: 'GEL', label: 'Georgian Lari', country: 'Georgia' },
        { value: 'GGP', label: 'Guernsey Pound', country: 'Guernsey' },
        { value: 'GHS', label: 'Ghanaian Cedi', country: 'Ghana' },
        { value: 'GIP', label: 'Gibraltar Pound', country: 'Gibraltar' },
        { value: 'GMD', label: 'Gambian Dalasi', country: 'The Gambia' },
        { value: 'GNF', label: 'Guinean Franc', country: 'Guinea' },
        { value: 'GTQ', label: 'Guatemalan Quetzal', country: 'Guatemala' },
        { value: 'GYD', label: 'Guyanese Dollar', country: 'Guyana' },
        { value: 'HKD', label: 'Hong Kong Dollar', country: 'Hong Kong' },
        { value: 'HNL', label: 'Honduran Lempira', country: 'Honduras' },
        { value: 'HRK', label: 'Croatian Kuna', country: 'Croatia' },
        { value: 'HTG', label: 'Haitian Gourde', country: 'Haiti' },
        { value: 'HUF', label: 'Hungarian Forint', country: 'Hungary' },
        { value: 'IDR', label: 'Indonesian Rupiah', country: 'Indonesia' },
        { value: 'ILS', label: 'Israeli New', country: 'Shekel Israel' },
        { value: 'IMP', label: 'Manx Pound', country: 'Isle of Man' },
        { value: 'INR', label: 'Indian Rupee', country: 'India' },
        { value: 'IQD', label: 'Iraqi Dinar', country: 'Iraq' },
        { value: 'IRR', label: 'Iranian Rial', country: 'Iran' },
        { value: 'ISK', label: 'Icelandic Króna', country: 'Iceland' },
        { value: 'JEP', label: 'Jersey Pound', country: 'Jersey' },
        { value: 'JMD', label: 'Jamaican Dollar', country: 'Jamaica' },
        { value: 'JOD', label: 'Jordanian Dinar', country: 'Jordan' },
        { value: 'JPY', label: 'Japanese Yen', country: 'Japan' },
        { value: 'KES', label: 'Kenyan Shilling', country: 'Kenya' },
        { value: 'KGS', label: 'Kyrgyzstani Som', country: 'Kyrgyzstan' },
        { value: 'KHR', label: 'Cambodian Riel', country: 'Cambodia' },
        { value: 'KID', label: 'Kiribati Dollar', country: 'Kiribati' },
        { value: 'KMF', label: 'Comorian Franc', country: 'Comoros' },
        { value: 'KRW', label: 'South Korean Won', country: 'South Korea' },
        { value: 'KWD', label: 'Kuwaiti Dinar', country: 'Kuwait' },
        { value: 'KYD', label: 'Cayman Islands Dollar', country: 'Cayman Islands' },
        { value: 'KZT', label: 'Kazakhstani Tenge', country: 'Kazakhstan' },
        { value: 'LAK', label: 'Lao Kip', country: 'Laos' },
        { value: 'LBP', label: 'Lebanese Pound', country: 'Lebanon' },
        { value: 'LKR', label: 'Sri Lanka Rupee', country: 'Sri Lanka' },
        { value: 'LRD', label: 'Liberian Dollar', country: 'Liberia' },
        { value: 'LSL', label: 'Lesotho Loti', country: 'Lesotho' },
        { value: 'LYD', label: 'Libyan Dinar', country: 'Libya' },
        { value: 'MAD', label: 'Moroccan Dirham', country: 'Morocco' },
        { value: 'MDL', label: 'Moldovan Leu', country: 'Moldova' },
        { value: 'MGA', label: 'Malagasy Ariary', country: 'Madagascar' },
        { value: 'MKD', label: 'Macedonian Denar', country: 'North Macedonia' },
        { value: 'MMK', label: 'Burmese Kyat', country: 'Myanmar' },
        { value: 'MNT', label: 'Mongolian Tögrög', country: 'Mongolia' },
        { value: 'MOP', label: 'Macanese Pataca', country: 'Macau' },
        { value: 'MRU', label: 'Mauritanian Ouguiya', country: 'Mauritania' },
        { value: 'MUR', label: 'Mauritian Rupee', country: 'Mauritius' },
        { value: 'MVR', label: 'Maldivian Rufiyaa', country: 'Maldives' },
        { value: 'MWK', label: 'Malawian Kwacha', country: 'Malawi' },
        { value: 'MXN', label: 'Mexican Peso', country: 'Mexico' },
        { value: 'MYR', label: 'Malaysian Ringgit', country: 'Malaysia' },
        { value: 'MZN', label: 'Mozambican Metical', country: 'Mozambique' },
        { value: 'NAD', label: 'Namibian Dollar', country: 'Namibia' },
        { value: 'NGN', label: 'Nigerian Naira', country: 'Nigeria' },
        { value: 'NIO', label: 'Nicaraguan Córdoba', country: 'Nicaragua' },
        { value: 'NOK', label: 'Norwegian Krone', country: 'Norway' },
        { value: 'NPR', label: 'Nepalese Rupee', country: 'Nepal' },
        { value: 'NZD', label: 'New Zealand Dollar', country: 'New Zealand' },
        { value: 'OMR', label: 'Omani Rial', country: 'Oman' },
        { value: 'PAB', label: 'Panamanian Balboa', country: 'Panama' },
        { value: 'PEN', label: 'Peruvian Sol', country: 'Peru' },
        { value: 'PGK', label: 'Papua New Guinean Kina', country: 'Papua New Guinea' },
        { value: 'PHP', label: 'Philippine Peso', country: 'Philippines' },
        { value: 'PKR', label: 'Pakistani Rupee', country: 'Pakistan' },
        { value: 'PLN', label: 'Polish Złoty', country: 'Poland' },
        { value: 'PYG', label: 'Paraguayan Guaraní', country: 'Paraguay' },
        { value: 'QAR', label: 'Qatari Riyal', country: 'Qatar' },
        { value: 'RON', label: 'Romanian Leu', country: 'Romania' },
        { value: 'RSD', label: 'Serbian Dinar', country: 'Serbia' },
        { value: 'RUB', label: 'Russian Ruble', country: 'Russia' },
        { value: 'RWF', label: 'Rwandan Franc', country: 'Rwanda' },
        { value: 'SAR', label: 'Saudi Riyal', country: 'Saudi Arabia' },
        { value: 'SBD', label: 'Solomon Islands Dollar', country: 'Solomon Islands' },
        { value: 'SCR', label: 'Seychellois Rupee', country: 'Seychelles' },
        { value: 'SDG', label: 'Sudanese Pound', country: 'Sudan' },
        { value: 'SEK', label: 'Swedish Krona', country: 'Sweden' },
        { value: 'SGD', label: 'Singapore Dollar', country: 'Singapore' },
        { value: 'SHP', label: 'Saint Helena Pound', country: 'Saint Helena' },
        { value: 'SLL', label: 'Sierra Leonean Leone', country: 'Sierra Leone' },
        { value: 'SOS', label: 'Somali Shilling', country: 'Somalia' },
        { value: 'SRD', label: 'Surinamese Dollar', country: 'Suriname' },
        { value: 'SSP', label: 'South Sudanese Pound', country: 'South Sudan' },
        { value: 'STN', label: 'São Tomé and Príncipe Dobra', country: 'São Tomé and Príncipe' },
        { value: 'SYP', label: 'Syrian Pound', country: 'Syria' },
        { value: 'SZL', label: 'Eswatini Lilangeni', country: 'Eswatini' },
        { value: 'THB', label: 'Thai Baht', country: 'Thailand' },
        { value: 'TJS', label: 'Tajikistani Somoni', country: 'Tajikistan' },
        { value: 'TMT', label: 'Turkmenistan Manat', country: 'Turkmenistan' },
        { value: 'TND', label: 'Tunisian Dinar', country: 'Tunisia' },
        { value: 'TOP', label: "Tongan Pa'anga", country: 'Tonga' },
        { value: 'TRY', label: 'Turkish Lira', country: 'Turkey' },
        { value: 'TTD', label: 'Trinidad and Tobago Dollar', country: 'Trinidad and Tobago' },
        { value: 'TVD', label: 'Tuvaluan Dollar', country: 'Tuvalu' },
        { value: 'TWD', label: 'New Taiwan Dollar', country: 'Taiwan' },
        { value: 'TZS', label: 'Tanzanian Shilling', country: 'Tanzania' },
        { value: 'UAH', label: 'Ukrainian Hryvnia', country: 'Ukraine' },
        { value: 'UGX', label: 'Ugandan Shilling', country: 'Uganda' },
        { value: 'USD', label: 'United States Dollar', country: 'United States' },
        { value: 'UYU', label: 'Uruguayan Peso', country: 'Uruguay' },
        { value: 'UZS', label: "Uzbekistani So'm", country: 'Uzbekistan' },
        { value: 'VES', label: 'Venezuelan Bolívar Soberano', country: 'Venezuela' },
        { value: 'VND', label: 'Vietnamese Đồng', country: 'Vietnam' },
        { value: 'VUV', label: 'Vanuatu Vatu', country: 'Vanuatu' },
        { value: 'WST', label: 'Samoan Tālā', country: 'Samoa' },
        { value: 'XAF', label: 'Central African CFA Franc', country: 'CEMAC' },
        { value: 'XCD', label: 'East Caribbean Dollar', country: 'Organisation of Eastern Caribbean States' },
        { value: 'XDR', label: 'Special Drawing Rights', country: 'International Monetary Fund' },
        { value: 'XOF', label: 'West African CFA franc', country: 'CFA' },
        { value: 'XPF', label: 'CFP Franc', country: "Collectivités d'Outre-Mer" },
        { value: 'YER', label: 'Yemeni Rial', country: 'Yemen' },
        { value: 'ZAR', label: 'South African Rand', country: 'South Africa' },
        { value: 'ZMW', label: 'Zambian Kwacha', country: 'Zambia' },
        { value: 'ZWL', label: 'Zimbabwean Dollar', country: 'Zimbabwe' },
    ]

    const [selectedOption, setSelectedOption] = useState('');

    const handleChange = selectedOption => {
        setSelectedOption(selectedOption);
        if (props.id == 1) {
            props.setCurrentCurrency(selectedOption.value);
        }
        else if (props.id == 2) {
            props.setDesiredCurrency(selectedOption.value);
        }
    };



    return (
        <div>
            <Select
                value={selectedOption}
                onChange={handleChange}
                options={options}
            />
        </div>
    );

};

export default TypeSelect1;


